# Generated by Django 4.2.6 on 2023-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_checked',
        ),
        migrations.AddField(
            model_name='user',
            name='user_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='почта подтверждена'),
        ),
    ]
