# Generated by Django 4.2.6 on 2023-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_email_checked_user_user_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.CharField(default=0, max_length=50, verbose_name='ключ пользователя'),
        ),
    ]
