# Generated by Django 4.2.5 on 2023-09-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100, verbose_name='описание'),
        ),
    ]
