# Generated by Django 4.2.5 on 2023-09-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0003_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='active_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hw.version', verbose_name='активная версия'),
        ),
    ]
