# Generated by Django 4.2.5 on 2023-09-26 08:25

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0004_remove_version_product_product_active_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='product_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='hw.product', verbose_name='продукт'),
        ),
    ]
