# Generated by Django 4.2.5 on 2023-09-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0005_version_product_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active_version',
        ),
    ]
