# Generated by Django 4.2.5 on 2023-09-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0006_remove_product_active_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hw.product', verbose_name='продукт'),
        ),
    ]
