# Generated by Django 4.2.5 on 2023-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0007_alter_version_product_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
